"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
import Navbar from "@/components/Navbar";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [token, setToken] = useState(null);
  useEffect(() => {
    if (typeof window !== "undefined" && window.localStorage) {
      const storedToken = localStorage.getItem("token");
      setToken(storedToken);
    }
  }, []);

  const client = new ApolloClient({
    uri: "http://localhost:5000/",
    cache: new InMemoryCache(),
    headers: {
      authorization: token ? `${token}` : "",
    },
  });

  return (
    <ApolloProvider client={client}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ApolloProvider>
  );
}
